Tencent/CodeAnalysis

plugins/jenkins_plugin/src/main/java/io/jenkins/plugins/StartClient.java
修复当jenkins任务中没有勾选全量扫描时，total=null导致isTotal=null，进而导致拼装命令时languageType后错误地拼上'null'的问题；
=> Jenkins插件命令拼装逻辑修正

server/dockerconfs/Dockerfile-common-mirror, server/dockerconfs/Dockerfile-common-normal
删除dockerfile中文注释；部分docker-compose版本（比如1.26.0）读取包含中文的dockerfile时会因编码问题导致读取不完整
=> :fire:删除Dockerfile中文注释

doc/zh/quickStarted/deploySever.md
1. 在官方文档中的`docker-compose`部署方式添加了数据库注意事项。
2. 因为MySQL的数据库没有`arm`版本。
=> add: docker-compose db services annotation.

scripts/base/install_db.sh, scripts/client/check.sh, scripts/config.sh, scripts/deploy/tca_local.sh
源码部署脚本支持检测客户端启动状态和配置外部db、redis
=> :art:优化源码部署脚本

client/node/toolloader/loadconfig.py, client/settings/base.py, client/util/envset.py
:art:优化工具依赖配置读取逻辑;
优化LD_LIBRARY_PATH环境变量处理;
废弃DEFAULT_TOOL_BASE_DIR
=> :art:优化工具依赖配置读取逻辑;优化LD_LIBRARY_PATH环境变量处理;废弃DEFAULT_TOOL_BASE_DIR

client/tool/clang.py
:art:clang工具 - 去掉UseNewBuildSystem参数；命令失败抛异常
=> :art:clang工具 - 去掉UseNewBuildSystem参数；命令失败抛异常

server/configs/requirements.txt, server/projects/analysis/requirements.txt, server/projects/file/requirements.txt, server/projects/main/requirements.txt
锁定importlib-metadata版本，避免celery模块加载失败
=> :pushpin:锁定importlib-metadata版本

server/projects/main/apps/scan_conf/management/commands/open_source/0daychecker.json, server/projects/main/apps/scan_conf/management/commands/open_source/flawfinder.json, server/projects/main/apps/scan_conf/management/commands/open_source/ktlint.json, server/projects/main/apps/scan_conf/management/commands/open_source/kunlunM.json, server/projects/main/apps/scan_conf/management/commands/open_source/phpcs.json, server/projects/main/apps/scan_conf/management/commands/open_source/rips.json, server/projects/main/apps/scan_conf/management/commands/open_source/semgrep.json, server/projects/main/apps/scan_conf/management/commands/open_source/shellcheck.json, server/projects/main/apps/scan_conf/management/commands/open_source/sqlcheck.json
=> :art:update custom-tool url

client/node/toolloader/gitload.py
:bug:修复工具拉取使用自定义鉴权场景下，成员变量未声明就使用问题（AttributeError: 'GitLoader' object has no attribute '_ssh_temp_file'）
=> :bug:修复工具拉取使用自定义鉴权场景下，成员变量未声明就使用问题

client/tool/util/tca_ql.py
=> :art: update tcaql py

server/projects/main/apps/scan_conf/management/commands/open_source/licenseclassifier.json, server/projects/main/apps/scan_conf/management/commands/open_source_package/license_check.json
=> ✨ add tool license-classifier json

server/dockerconfs/Dockerfile-nginx-mirror, server/projects/analysis/requirements.txt, server/projects/main/requirements.txt, server/projects/scmproxy/requirements.txt
修复本地构建的一些问题
1、修改所有 requirements
urllib3==1.26.7 为 urllib3==1.26.11 可以构建成功
2、nginx镜像 debian 9 的地址更改了，debian-archive 可以构建成功
=> fix:docker build

Dockerfile
* 场景：
使用main分支代码进行打包镜像`TCA_IMAGE_BUILD=true ./quick_install.sh docker deploy`
时，执行报错
``` log
4273.2 + bash /tmp/mariadb_repo_setup --mariadb-server-version=mariadb-10.6
4273.2 # [error] Detected Debian but version (12.0) is not supported.
4273.2 # [error] # The MariaDB Repository only supports these distributions:
4273.2 #    * RHEL/Rocky 8 & 9 (rhel)
4273.2 #    * RHEL/CentOS 7 (rhel)
4273.2 #    * Ubuntu 18.04 LTS (bionic), 20.04 LTS (focal), and 22.04 LTS (jammy)
4273.2 #    * Debian 10 (buster), & 11 (bullseye)
4273.2 #    * SLES 12 & 15 (sles)
4273.2 # [error] # See https://mariadb.com/kb/en/mariadb/mariadb-package-repository-setup-and-usage/#platform-support
```
* 分析：
python:3.7-slim （Image hierarchy From debian:12-slim），而MariaDB-10.6不支持Debian-12 
基础镜像操作系统升级后导致兼容
* 解决： …
=> :art:完善Docker构建解决原基础镜像Debian-12.0与mariadb-10.6不兼容问题

client/Dockerfile
:bug:修复挂载的代码目录owner不是root时，导致git blame异常 - fatal: unsafe repository ('/xxx/xxx' is owned by someone else)
=> :bug:修复挂载的代码目录owner不是root时，导致git blame异常

client/README.md, doc/en/guide/客户端/本地分析.md, doc/zh/guide/客户端/本地分析.md
=> :art:更新客户端使用文档

client/Dockerfile
:bento: libreadline.so.6在lua场景分析的时候报错
https://askubuntu.com/questions/1168787/libreadline-so-6-issue-in-ubuntu-18-04
用tca-client 镜像启动lua分析，如果不解决这个问题，分析工具一定报错
通过这个修改，我自己生成一个镜像 docker pull zzzfwww/tca-client，用这个镜像就解决这个报错，修改如上
=> :bug: 修复dockerfile缺少工具

doc/en/quickStarted/enhanceDeploy.md, doc/zh/quickStarted/enhanceDeploy.md
=> update enhanceDeploy md

doc/en/quickStarted/enhanceDeploy.md, doc/zh/quickStarted/enhanceDeploy.md
-  :memo: update enhance deploy md
=>  :memo: update enhance deploy md

scripts/config.sh, server/dockerconfs/.env.local, server/dockerconfs/Dockerfile-common-mirror, server/projects/login/apps/settings/open_base.py, server/projects/login/login/apis/v3.py, server/projects/login/requirements.txt
我司在 2023 年选择使用 [CodeAnalysis](https://github.com/Tencent/CodeAnalysis) 作为白盒代码扫描平台，主要考虑是整体功能与需求匹配度较高，是开源的并且社区活跃度也不错，基于 Django 框架二次开发也容易上手，整体架构清晰有良好的代码风格，相关文档和运行日志也很齐全。
本次 PR 需求来自 https://github.com/Tencent/CodeAnalysis/issues/610 
注意到近期有相同需求的用户越来越多 ，所以考虑贡献代码
CodeAnalysis 不考虑认证源是什么，只关心是否认证成功，所以只需要在认证逻辑里添加 ldap 认证的代码就可以
1. CodeAnalysis 使用微服务架构，先更新配置 login APP open_base.py 支持 LDAP
2. CodeAnalysis 使用 Django 自带的权限系统，只需修改在 Login 微服务里 **CodeAnalysis/server/projects/login/login/apis/v3.py**  OAInfoAPIView 类，把这部分 「登录认证」代码修改为先通过 LDAP 认证，如果认证通过并且获取 or 创建账号成功就生成 access_token 等认证成功参数，如果不通过就使用 CodeAnalysis 默认的登录方式。
在使用前请先根据具体 LDAP 服务情况修改以下三个文件
1. CodeAnalysis/scripts/config.sh
2. CodeAnalysis/server/dockerconfs/.env.local
3. CodeAnalysis/server/projects/login/apps/settings/open_base.py …
=> feature: supports LDAP

client/tool/regexscanner.py
=> :art:updat comment

Dockerfile, server/configs/requirements.txt
=> dockerfile和依赖包修改

server/configs/django/local_analysis.py, server/configs/django/local_main.py, server/projects/analysis/apps/base/management/commands/clear_analysis_data.py, server/projects/analysis/apps/codemetric/models/cc.py, server/projects/analysis/apps/codeproj/api_urls/v1_tiyan_project.py, server/projects/analysis/apps/codeproj/apis/v1.py, server/projects/main/apps/base/management/commands/clear_deleted_project.py, server/projects/main/util/webclients.py
增加“历史数据清理”脚本，添加远程调用软删除功能，添加适配django3.2的默认主键类型配置。
=> “增加“历史数据清理”脚本”

doc/zh/guide/插件/Jenkins_Plugin.md, plugins/jenkins_plugin/pom.xml, plugins/jenkins_plugin/src/main/java/io/jenkins/plugins/TCABuilder.java
=> Jenkins插件功能优化

scripts/deploy/tca_docker.sh
docker部署过程中，会遇到报错“Error: The minimum number of file descriptors required to run this process is 10240 as per the "minfds" command-line argument or config file setting. The current environment will only allow you to open 10240 file descriptors. Either raise the number of usable file descriptors in your environment (see README.rst) or lower the minfds setting in the config file to allow the process to start.
For help, use /usr/local/bin/supervisord -h + ret=2
+ set +x
[2024/07/23 18:01:27] [ERROR]: Deploy tca docker failed”
解决办法：需要扩充docker ulimit数而不是系统的ulimit
在/CodeAnalysis/scripts/deploy/tca_docker.sh中添加代码"--ulimit nofile=10240:10240"
如图所示
=> 添加了'--ulimit nofile=10240:10240'

doc/en/guide/插件/Jenkins_Plugin.md, doc/zh/guide/插件/Jenkins_Plugin.md
上一次提交中脚本示例中的TCA_Builder忘记修改为TCA，此次提交将TCA_Builder改为TCA，在pipeline部分增加release版本可能未修改的说明，并贴上了对应问题的链接。同时修改了英文版文档
=> 完善Jenkins文档

helm-charts/tca/templates/main/servicemonitor.yaml, server/projects/main/apps/nodemgr/api_urls/v1.py, server/projects/main/apps/nodemgr/apis/v1.py
增加“节点池中空闲节点情况”相关的prometheus监控数据metrics
=> 增加“节点池中空闲节点情况”相关的prometheus监控数据metrics

.github/workflows/sync.yml
=> :art:update sync

.cnb.yml
:art:update .cnb.yml, change to incr scan
=> :art:update .cnb.yml, change to incr scan
