Tencent/CodeAnalysis

client/config.ini

增加拉取工具相关的可选配置项：USE_LOCAL_TOOL，TOOL_LOAD_ACCOUNT

增加拉取工具相关的可选配置项

---

client/README.md

:art:更新client README.md，新增工具库配置和用法

---

client/node/loadtool.py

:art:增加使用本地工具的提示信息

---

client/README.md

:art:更新client README.md，增加git lfs配额不足解决方法

:art:更新client README.md，增加git lfs配额不足解决方法

---

doc/references/install_python37_on_centos.md

检查python -v输出结果是否为python-3.7.12版本，否则会影响后续安装

更新了要求检查python版本的注释

---

README.md

:art:调整tca英文说明

---

client/Dockerfile
client/README.md
client/tool/util/pythontool.py

1. 增加在docker中使用client的方式
2. 避免PYTHON_VERSION环境变量影响

🎨 :增加在docker中使用client的方式

---

plugins/jenkins_plugin/src/main/java/io/jenkins/plugins/StartClient.java
plugins/jenkins_plugin/src/main/java/io/jenkins/plugins/TCABuilder.java

获取环境变量优化并更新插件使用说明

---

doc/Q&A.md
docker-compose.yml
server/dockerconfs/Dockerfile-common
server/scripts/init_config.sh

:art:调整pypi下载失败提示

---

plugins/jenkins_plugin/src/main/java/io/jenkins/plugins/TCABuilder.java

修改参数isTotal(是否开启全量扫描)判断方式

---

web/tca-deploy-source/config.sh
web/tca-deploy-source/init.sh
web/tca-deploy-source/nginx/document.conf
web/tca-deploy-source/nginx/framework_template.conf
web/tca-deploy-source/nginx/ingress.conf
web/tca-deploy-source/nginx/template.conf
web/tca-deploy-source/reset.sh

1.修复了WEB_DEPLOY_PATH配置参数没有在nginx的*.conf配置文件中进行替换的问题；
2.添加了WEB_DEPLOY_PATH参数，用于替换nginx的*.conf配置文件中access_log与error_log的保存位置；
3.修正变量名拼写错误 NINGX_CONF_PATH -> NGINX_CONF_PATH；

web模块部署脚本问题修复及优化

---

client/settings/base.py
server/projects/main/apps/scan_conf/management/commands/open_source/0daychecker.json
server/projects/main/apps/scan_conf/management/commands/open_source_package/Log4j漏洞.json
server/projects/main/apps/scan_conf/management/commands/open_source_package/logback.json

:beer: add tool-0daychecker

---

doc/Q&A.md
doc/deploy_dc.md
quick_install.sh
server/scripts/deploy_test_docker.sh

1. 调整部署脚本执行注意事项
2. 补充pypi下载异常的处理步骤
3. 调整docker检测脚本

:art:完善部署和Q&A文档

---

README.md
README_ZH.md

增加工蜂仓库镜像链接

---

client/README.md
client/config.ini

:art:增加腾讯工蜂作为工具拉取源，可选用

---

.gitignore
client/codepuppy.py
client/node/common/cmdarg.py
client/test/test_codepuppy.py

- 修复codepuppy.py无参数执行异常错误
- 调整git忽略文件列表

修复codepuppy.py无参数执行异常错误

---

client/README.md
server/projects/main/apps/codeproj/models/base.py
server/projects/main/codedog/settings/open_base.py
server/projects/main/util/scm/svn.py

调整工程配置和文档，支持https克隆

---

server/projects/analysis/apps/codelint/job/linthandler.py

:bug:修复issue入库忽略处理操作

---

tools/loong/README.md

:memo: update loong doc

---

tools/README.md

:memo: update tools readme

---

server/projects/file/codedog_file_server/settings.py
server/projects/scmproxy/requirements.txt

1. 补充scmproxy缺失依赖
2. 调整fileserver日志输出文件名称

:bug:补充缺失依赖

---

doc/old/references/install_nginx_from_source.md
doc/zh/quickStarted/references/install_nginx_from_source.md
docker-compose.yml

1. docker-compose支持挂载本地日志目录
2. 完善nginx源码安装文档

:art:docker-compose部署支持挂载本地日志目录

---

server/projects/main/apps/base/api_urls/base.py

add healthcheck in route of main server

---

client/README.md

:art:更新client README.md

---

server/projects/main/apps/codeproj/migrations/0004_auto_20220608_2344.py
server/projects/main/apps/job/api_urls/v2_job.py
server/projects/main/apps/job/apis/base.py
server/projects/main/apps/job/models/base.py
server/scripts/init_config.sh

:art:增加子任务接口，完善部署脚本

---

plugins/jenkins_plugin/README.md

jenkins plugin Installation package

增加jenkins plugin Installation package链接

---

server/configs/django/local_analysis.py
server/configs/django/local_main.py
server/projects/analysis/util/fileserver.py
server/projects/main/apps/codeproj/api_urls/v1_org.py
server/projects/main/apps/codeproj/apis/v1.py
server/projects/main/apps/codeproj/apis/v1_scheme.py
server/projects/main/apps/codeproj/core/jobmgr.py
server/projects/main/apps/codeproj/permissions.py
server/projects/main/apps/codeproj/serializers/v3.py
server/projects/main/codedog/open_urls.py
server/projects/main/util/fileserver.py
server/projects/main/util/time.py

1. 开放团队维度扫描方案模板接口API
2. 增加扫描方案模板任务参数API
3. 优化文件服务器鉴权交互

:sparkles:增加扫描方案模板API&优化文件服务器鉴权交互

---

scripts/base/install_db.sh
scripts/base/install_nginx.sh
scripts/base/install_python.sh
scripts/utils.sh

:sparkles:支持源码安装Redis与Nginx

---

docker-start.sh
docker-stop.sh

macOS系统，安装了docker环境后，启动docker desktop便于管理环境与查看tca容器等
执行docker_start脚本启动desktop之后再执行quick_start脚本
执行docker_stop脚本停止desktop

macOS启动docker desktop

---

client/task/basic/datahandler/packdiffinfo.py

:bug:修复方法调用不存在问题

---

client/task/basic/datahandler/packdiffinfo.py

:bug: fix get_block_change_type call

:bug: fix get_block_change_type call

---

client/README.md

:art:update client README.md docker模式

:art:update client README.md docker模式

---

server/projects/login/login/apis/v3.py
server/projects/login/login/lib/rendererresponse.py
server/projects/login/login/middleware/loginmiddleware.py

:art:完善登录接口异常处理和错误提示

---

docker-compose.yml
scripts/docker/start.sh

docker与docker-compose部署方式支持挂载client配置文件

:art:docker与docker-compose支持挂载client配置文件

---

server/projects/main/apps/scan_conf/management/commands/open_source/compass.json

:art: Update rules

---

server/projects/main/apps/scan_conf/management/commands/open_source_package/front_end_framework_check.json

:art:新增前端框架识别规则包

---

client/Dockerfile

:bug:client镜像补充openssh-client依赖

---

doc/en/README.md
doc/en/guide/快速入门/快速启动一次代码分析.md
doc/en/quickStarted/dockerDeploy.md

这份PR提交了docker快速部署的英文~~翻译~~意译
[CONTRIBUTING.md](https://github.com/Tencent/CodeAnalysis/blob/dev/change-doc-home-actions/CONTRIBUTING.md)说我应该向dev分支提交PR，但是我无法确定dev/change-doc-home-actions分支是否就是这个所谓的“dev”分支，在[这里的说明](https://github.com/Tencent/CodeAnalysis/discussions/234)，图片中提示向main分支提交PR，我也不确定我应该向哪个分支提交PR。如果我选择了错误的分支，请海涵由此带来的不便。

Translation for dockerDeploy.md

---

client/task/puppytask.py
client/tool/codecount.py
client/tool/cpplint.py

1. :art:cpplint、codecoutn适配QuickScan场景
2. :art:task.log打印堆栈信息，方便排查问题

:art:cpplint、codecoutn适配QuickScan场景

---

client/tool/util/collie.py
doc/.vuepress/configs/sidebar/en.ts
doc/.vuepress/configs/sidebar/zh.ts
doc/en/guide/工具管理/工具列表.md
doc/zh/guide/工具管理/工具列表.md

:bug: fix KeyError

---

client/tool/util/collie.py
doc/.vuepress/configs/sidebar/en.ts
doc/.vuepress/configs/sidebar/zh.ts

:mute: remove useless log

---

client/tool/flow.py
client/tool/util/infer.py

update tool-infer and tool-flow

:art:update tool-infer and tool-flow

---

doc/zh/quickStarted/FAQ.md

补充常见问题以及解决方案：代码库登记成功后，开启第一次代码分析时，出现代码库及账号不匹配

[WeOpen Star] 补充文档常见问题以及解决方案

---

doc/zh/quickStarted/FAQ.md

[WeOpen Star] 补充文档：服务启动时报错的一种case的排查方式

---

doc/zh/quickStarted/FAQ.md

:art:完善FAQ文档关于codedog_env配置的说明

:art:完善FAQ文档关于codedog_env配置的说明

---

client/tool/cppcheck.py
client/tool/cppcheck2.py
server/projects/main/apps/scan_conf/management/commands/open_source/cppcheck2.json

🎨cppcheck2.6工具支持misra检查规则

---

server/configs/django/local_analysis.py
server/configs/django/local_file.py
server/configs/django/local_login.py
server/configs/django/local_main.py
server/dockerconfs/.env.local
server/projects/main/apps/codeproj/core/projmgr.py
server/projects/main/apps/codeproj/models/base.py
server/projects/main/apps/codeproj/serializers/base.py

:bug:修复项目删除逻辑

---

client/node/localtask/filtermgr.py
client/node/localtask/requestgenerator.py

:bug:修复localscan设置扫描目录后，分析方案配置的过滤路径不生效问题

:bug:修复localscan设置扫描目录后，分析方案配置的过滤路径不生效问题

---

client/tool/cpplint.py

🎨 tool-cpplint优化路径传入

---

server/projects/main/apps/scan_conf/management/commands/open_source/pyright.json

feat:  add pyright tool

---

doc/en/quickStarted/enhanceDeploy.md
doc/zh/quickStarted/enhanceDeploy.md

- :memo: update enhance deploy md

:memo: update enhance deploy md

---

client/README.md
client/config.ini
doc/en/guide/客户端/其他配置.md
doc/en/guide/客户端/配置说明.md
doc/zh/guide/客户端/其他配置.md
doc/zh/guide/客户端/配置说明.md

:art:修正文档说明 - 客户端tools目录；腾讯工蜂账号配置说明

:art:修正文档说明 - 客户端tools目录；腾讯工蜂账号配置说明

---

doc/en/quickStarted/enhanceDeploy.md
doc/zh/quickStarted/enhanceDeploy.md

:memo: update email

---

doc/en/quickStarted/enhanceDeploy.md
doc/zh/quickStarted/enhanceDeploy.md

 :memo: 增加CLS网络异常排查指引

---

client/node/toolloader/loadconfig.py

:bug:工具依赖 - 修复依赖方案条件为空时会误判为符合条件的情况

:bug:工具依赖 - 修复依赖方案条件为空时会误判为符合条件的情况

---

client/tool/luacheck.py

luacheck: fix msg

---

quick_install.sh
scripts/base/get_os.sh
scripts/base/install_git_lfs.sh

本次提交增加了“自动安装git_lfs”功能的脚本，以及"判断操作系统"功能的脚本。

增加"安装gitlfs"和"判断操作系统"脚本

---

client/Dockerfile
client/README.md

:art:client dockerfile 兼容arm64

:art:client dockerfile 兼容arm64

---

doc/zh/api/代码度量数据模块接口.md
doc/zh/api/代码扫描数据模块接口.md
doc/zh/api/任务管理模块接口.md
doc/zh/api/结果概览模块接口.md
doc/zh/api/项目管理模块接口.md

增加“api参数是否必填”的提示

---

scripts/base/install_bin.sh

:arrow_up: update tca lib

---

ScriptsAPI.py

增加“api调用demo脚本”

---

doc/en/quickStarted/enhanceDeploy.md
doc/zh/quickStarted/enhanceDeploy.md

- :memo: update enhanced deploy md

:memo: update enhanced deploy md

---

client/tool/luacheck.py

:bug:修复luacheck在windows下处理结果异常的问题

---

helm-charts/tca/README.md
helm-charts/tca/templates/client/configmap-conf.yaml
helm-charts/tca/templates/ingress.yml
helm-charts/tca/values.yaml
server/projects/main/Dockerfile
web/Dockerfile

修改web、server部分的dockerfile配置，修改values.yaml和ingress.yml配置，文档中增加imagePullSecrets配置说明。

修改“helm charts 部署方式的相关配置”

---

server/projects/login/login/models.py

解决helm charts部署项目，账户无法登录的问题

---

helm-charts/tca/README.md
helm-charts/tca/templates/client/deployment-default.yaml
helm-charts/tca/templates/client/deployment-extra.yaml
helm-charts/tca/values.yaml

增加“helm charts部署方式下的节点池扩容功能”及文档说明

增加“helm charts部署方式下的节点池扩容功能”及文档说明

---

client/node/localtask/codecounttask.py
client/node/localtask/localrunner.py
client/node/localtask/requestmodify.py
client/node/localtask/runlocaltask.py
client/node/servertask/looprunner.py
scripts/base/install_bin.sh

增加客户端渠道信息打印

---

server/configs/requirements.txt
server/projects/analysis/requirements.txt
server/projects/file/requirements.txt
server/projects/login/requirements.txt
server/projects/main/requirements.txt
server/projects/scmproxy/requirements.txt

sentry-sdk组件版本升级

---

scripts/base/install_bin.sh

:bug: 适配低版本的shell写法

---

helm-charts/tca/README.md
helm-charts/tca/templates/analysis/configmap.yaml
helm-charts/tca/templates/file/configmap-env.yaml
helm-charts/tca/templates/login/configmap.yaml
helm-charts/tca/templates/main/configmap.yaml
helm-charts/tca/values.yaml
server/projects/analysis/analysis.gunicorn.conf.py
server/projects/file/file.gunicorn.conf.py
server/projects/login/login.gunicorn.conf.py
server/projects/main/main.gunicorn.conf.py

增加gunicorn多个工作进程共享指标数据的功能，及清理过期的共享db文件。

增加gunicorn架构上报指标配置

---

client/codepuppy.py
client/node/common/printversion.py
client/node/localtask/urlclient.py
client/util/logutil.py
client/util/pyinstallerlib.py
scripts/base/install_bin.sh

1. 调整客户端版本信息输出日志
2. 更新用户信息页url
3. 更新tca_lib

:art:调整客户端版本信息输出日志

---

server/projects/main/apps/scan_conf/management/commands/open_source/pmd.json

:art: update pmd json

---

scripts/base/install_bin.sh

:art: Adapt to cnb

---

CONTRIBUTING.md
README.md
README_ZH.md
doc/en/community/contribute.md
doc/zh/community/contribute.md

Commit 065a3f964e4c4ab970f601e8ba376cc040988af5 renamed the license from `LICENSE` to `LICENSE.txt`. This PR adjusts sources to changes.

Update license reference

---

.cnb.yml

:art:修复.cnb.yml缩进问题
